// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_level = "CgkIjaqpjPgJEAIQCg"; // <GPGSID>
        public const string achievement_level_9_999 = "CgkIjaqpjPgJEAIQCQ"; // <GPGSID>
        public const string achievement_level_50 = "CgkIjaqpjPgJEAIQAg"; // <GPGSID>
        public const string achievement_level_100 = "CgkIjaqpjPgJEAIQAw"; // <GPGSID>
        public const string achievement_level_500 = "CgkIjaqpjPgJEAIQBQ"; // <GPGSID>
        public const string achievement_level_10 = "CgkIjaqpjPgJEAIQAA"; // <GPGSID>
        public const string achievement_level_20 = "CgkIjaqpjPgJEAIQAQ"; // <GPGSID>
        public const string achievement_level_5_000 = "CgkIjaqpjPgJEAIQCA"; // <GPGSID>
        public const string achievement_level_2_000 = "CgkIjaqpjPgJEAIQBw"; // <GPGSID>
        public const string achievement_level_1_000 = "CgkIjaqpjPgJEAIQBg"; // <GPGSID>
        public const string achievement_level_200 = "CgkIjaqpjPgJEAIQBA"; // <GPGSID>

}

